<a href="https://colab.research.google.com/github/Dev-Arhaan/PyTorch_Dbourke/blob/main/00_pyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [3]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2526, 0.1275, 0.3236, 0.8875],
        [0.7010, 0.9939, 0.5071, 0.1976],
        [0.7186, 0.1412, 0.9338, 0.2458]])

In [5]:
# Finding out details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2526, 0.1275, 0.3236, 0.8875],
        [0.7010, 0.9939, 0.5071, 0.1976],
        [0.7186, 0.1412, 0.9338, 0.2458]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (Performing Operations)

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [6]:
# create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [7]:
# multiply a tensor

tensor * 10

tensor([10, 20, 30])

In [8]:
# built-in functions of pytorch
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [9]:
torch.matmul(tensor,tensor)

tensor(14)

In [10]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.7462, 0.4323, 1.0336],
        [0.3086, 0.1653, 0.4370],
        [0.4592, 0.5317, 0.4489]])

In [11]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8207, 0.9988],
        [0.8365, 0.9022]])

In [14]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

#tensor_B.T

torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A,tensor_B.T)

In [30]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [23]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [24]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [27]:
# Note: torch.mean() function requires float 32 dtype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [28]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [31]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [35]:
x.argmax()


tensor(9)

In [37]:
x[9]

tensor(91)

### Reshaping, Stacking, Squeezing, UnSqueezing tensors

* Reshaping -  reshapes an input tensor to a defined shape
* View - same memory, new shape
* Stack - combines multiple tensors on top of each other(Vstack) or side by side(Hstack)
* Squeeze -removes all `1` dimensions from a tensor
* unsqueeze - add `1` dimension to target tensor
* permute - return view of input with dimensions swapped in a certian way

In [38]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [47]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [48]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))